DROP DATABASE IF EXISTS ikea;

CREATE DATABASE ikea;

\c ikea;

DROP TABLE IF EXISTS product CASCADE;

CREATE TABLE product (
	id INT UNIQUE PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	material_ids INT[] NOT NULL,
	image_ids INT[] NOT NULL,
	detail_id INT NOT NULL REFERENCES detail (id),
	package_id INT NOT NULL REFERENCES package (id)
);

DROP TABLE IF EXISTS image CASCADE;

CREATE TABLE image (
  id INT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
  url VARCHAR (200) NOT NULL
);

DROP TABLE IF EXISTS material CASCADE;

CREATE TABLE material (
	id INT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
	name VARCHAR (100) NOT NULL,
	description TEXT NOT NULL
);

DROP TABLE IF EXISTS package CASCADE;

CREATE TABLE package (
  id INT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
  name VARCHAR (100) NOT NULL,
  description TEXT NOT NULL,
  dimensions VARCHAR (50) NOT NULL,
  weight VARCHAR (10) NOT NULL
);

DROP TABLE IF EXISTS detail CASCADE;

CREATE TABLE detail (
	id INT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY,
	designer VARCHAR (50) NOT NULL,
	care VARCHAR (200) NOT NULL
);

DROP TABLE IF EXISTS member CASCADE;

CREATE TABLE member (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	name VARCHAR (100) NOT NULL,
	last VARCHAR (100) NOT NULL,
	username VARCHAR (100) NOT NULL,
	password VARCHAR (100) NOT NULL,
	sex CHAR (1) NOT NULL,
	email VARCHAR (100) NOT NULL,
	city VARCHAR (100) NOT NULL,
	state VARCHAR (100) NOT NULL,
	zip CHAR (12) NOT NULL,
	created_at DATE NOT NULL,
	updated_at DATE NULL
);